const canvas = document.querySelector('#gameCanvas');
const ctx = canvas.getContext('2d');
const stage = document.querySelector('#gameStage');
const screens = ['startScreen','tutorialScreen','countdownScreen','resultScreen'].map(id=>document.getElementById(id));
const ui = Object.fromEntries(['hud','score','time','combo','finalScore','germsKilled','maxCombo','mistakes','rankTitle','gazeCursor','feedback','practiceGerm','lockStatus','tutorialText','countdownValue','stageHelp'].map(id=>[id,document.getElementById(id)]));

let state='start', last=0, elapsed=0, score=0, combo=0, bestCombo=0, killed=0, mistakes=0;
let objects=[], particles=[], cursor={x:0,y:0,inside:false}, gazeTarget=null, gazeSince=0, practiceSince=0, practiceLocked=false, soundOn=true;
const GAME_TIME=45;

function resize(){const r=stage.getBoundingClientRect(); const dpr=Math.min(devicePixelRatio,2); canvas.width=r.width*dpr; canvas.height=r.height*dpr; canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize); resize();
const size=()=>({w:stage.clientWidth,h:stage.clientHeight});
function show(id){screens.forEach(s=>{s.hidden=s.id!==id});}
function rand(a,b){return a+Math.random()*(b-a)}
function roundedBlobPath(x,y,r,t=0){ctx.beginPath();for(let i=0;i<=12;i++){const a=i/12*Math.PI*2;const rr=r*(1+Math.sin(a*3+t)*.09);const px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr*.84;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}

class Cell{
  constructor(type){const {w,h}=size();this.type=type;this.x=rand(-80,w+80);this.y=rand(120,h-90);this.r=type==='red'?rand(22,40):type==='boss'?64:rand(22,34);this.vx=rand(18,45)*(Math.random()<.5?-1:1);this.vy=rand(-12,12);this.t=rand(0,10);this.hp=type==='boss'?3:1;this.value=type==='fast'?20:type==='boss'?50:10}
  update(dt){const {w,h}=size();this.x+=this.vx*dt;this.y+=this.vy*dt;this.t+=dt;if(this.x<-100)this.x=w+80;if(this.x>w+100)this.x=-80;if(this.y<110||this.y>h-70)this.vy*=-1}
  draw(){ctx.save();ctx.translate(this.x,this.y);if(this.type==='red'){ctx.rotate(Math.sin(this.t)*.25);ctx.fillStyle='#ef476f';ctx.beginPath();ctx.ellipse(0,0,this.r,this.r*.52,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b82950';ctx.beginPath();ctx.ellipse(0,0,this.r*.5,this.r*.22,0,0,Math.PI*2);ctx.fill()}else{const color=this.type==='fast'?'#9f6cff':this.type==='boss'?'#ff784f':'#87dc62';ctx.shadowColor=color;ctx.shadowBlur=gazeTarget===this?24:10;ctx.fillStyle=color;roundedBlobPath(0,0,this.r,this.t);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='white';ctx.beginPath();ctx.arc(-this.r*.28,-5,5,0,7);ctx.arc(this.r*.28,-5,5,0,7);ctx.fill();ctx.fillStyle='#142014';ctx.beginPath();ctx.arc(-this.r*.28,-4,2,0,7);ctx.arc(this.r*.28,-4,2,0,7);ctx.fill();ctx.strokeStyle='#243c27';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,this.r*.18,this.r*.27,0,Math.PI);ctx.stroke();if(this.type==='boss'){ctx.fillStyle='#32101c';ctx.fillRect(-50,-this.r-18,100,7);ctx.fillStyle='#ffd166';ctx.fillRect(-50,-this.r-18,100*(this.hp/3),7)}}ctx.restore()}
  hit(x,y){return Math.hypot(x-this.x,y-this.y)<this.r*1.2}
}
class Particle{constructor(x,y,color){this.x=x;this.y=y;this.vx=rand(-100,100);this.vy=rand(-120,30);this.life=1;this.color=color}update(dt){this.life-=dt*2;this.x+=this.vx*dt;this.y+=this.vy*dt}draw(){ctx.globalAlpha=Math.max(0,this.life);ctx.fillStyle=this.color;ctx.beginPath();ctx.arc(this.x,this.y,rand(2,5),0,7);ctx.fill();ctx.globalAlpha=1}}

function drawVessel(t){const {w,h}=size();const g=ctx.createRadialGradient(w*.5,h*.5,30,w*.5,h*.5,Math.max(w,h)*.65);g.addColorStop(0,'#70163e');g.addColorStop(.55,'#4b0b30');g.addColorStop(1,'#22091f');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(255,92,130,.23)';ctx.lineWidth=34;ctx.beginPath();ctx.moveTo(-50,h*.18);ctx.bezierCurveTo(w*.25,h*.1,w*.6,h*.3,w+50,h*.15);ctx.moveTo(-50,h*.85);ctx.bezierCurveTo(w*.35,h*.67,w*.7,h*.96,w+50,h*.74);ctx.stroke();for(let i=0;i<12;i++){const x=(i*173+t*12)%(w+160)-80,y=h*(.2+((i*67)%60)/100);ctx.fillStyle='rgba(255,130,150,.1)';ctx.beginPath();ctx.ellipse(x,y,50,18,.3,0,7);ctx.fill()}}
function spawn(){const progress=elapsed/GAME_TIME;if(elapsed>36&&!objects.some(o=>o.type==='boss'))objects.push(new Cell('boss'));const germCount=objects.filter(o=>o.type!=='red'&&o.type!=='boss').length;if(germCount<2+Math.floor(progress*4))objects.push(new Cell(progress>.38&&Math.random()<.36?'fast':'germ'));if(objects.filter(o=>o.type==='red').length<4)objects.push(new Cell('red'))}
function updateGaze(){if(state!=='playing'||!cursor.inside){gazeTarget=null;return}const target=[...objects].reverse().find(o=>o.hit(cursor.x,cursor.y));if(target!==gazeTarget){gazeTarget=target;gazeSince=performance.now()}ui.gazeCursor.classList.toggle('locked',!!target&&performance.now()-gazeSince>180)}
function attack(){if(state==='tutorial'){if(practiceLocked){burst(stage.clientWidth/2,stage.clientHeight*.58,'#8ee36d');startCountdown()}return}if(state!=='playing'||!gazeTarget||performance.now()-gazeSince<180)return;const o=gazeTarget;if(o.type==='red'){score=Math.max(0,score-10);combo=0;mistakes++;feedback('-10  적혈구 보호!','#ff7896');gazeTarget=null;return}o.hp--;burst(o.x,o.y,o.type==='fast'?'#b88cff':'#8ee36d');if(o.hp<=0){objects=objects.filter(x=>x!==o);score+=o.value;combo++;killed++;bestCombo=Math.max(bestCombo,combo);if(combo>0&&combo%5===0){score+=30;feedback('COMBO BONUS +30','#ffd166')}else feedback(`+${o.value}`,'#8ee36d')}else feedback(`보스 ${o.hp}회 남음`,'#ffd166');gazeTarget=null;updateHUD()}
function burst(x,y,color){for(let i=0;i<18;i++)particles.push(new Particle(x,y,color));tone(280,0.06)}
function feedback(text,color){ui.feedback.textContent=text;ui.feedback.style.color=color;ui.feedback.classList.remove('pop');void ui.feedback.offsetWidth;ui.feedback.classList.add('pop')}
function tone(freq,dur){if(!soundOn)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+dur);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch{}}
function updateHUD(){ui.score.textContent=String(score).padStart(3,'0');ui.combo.textContent=`× ${combo}`;ui.time.textContent=Math.max(0,Math.ceil(GAME_TIME-elapsed))}

function beginTutorial(){state='tutorial';show('tutorialScreen');practiceSince=0;practiceLocked=false;ui.practiceGerm.classList.remove('locked');ui.lockStatus.textContent='GAZE SEARCHING';ui.lockStatus.classList.remove('ready')}
function startCountdown(){state='countdown';show('countdownScreen');let n=3;ui.countdownValue.textContent=n;const timer=setInterval(()=>{n--;if(n>0){ui.countdownValue.textContent=n;tone(180+n*60,.08)}else{clearInterval(timer);startGame()}},700)}
function startGame(){state='playing';show('');ui.hud.hidden=false;ui.stageHelp.hidden=false;elapsed=0;score=combo=bestCombo=killed=mistakes=0;objects=[];particles=[];for(let i=0;i<4;i++)objects.push(new Cell('red'));for(let i=0;i<2;i++)objects.push(new Cell('germ'));updateHUD();tone(420,.12)}
function endGame(){state='result';ui.hud.hidden=true;const rank=score>=450?'건강수호대 마스터':score>=300?'건강수호대 영웅':score>=150?'건강수호대 대원':'건강수호대 새싹';ui.rankTitle.textContent=rank;ui.finalScore.textContent=score;ui.germsKilled.textContent=killed;ui.maxCombo.textContent=bestCombo;ui.mistakes.textContent=mistakes;show('resultScreen');tone(520,.3)}
function reset(){state='start';objects=[];particles=[];ui.hud.hidden=true;ui.stageHelp.hidden=false;show('startScreen')}

function frame(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;drawVessel(now/1000);if(state==='playing'){elapsed+=dt;spawn();objects.forEach(o=>o.update(dt));updateGaze();if(elapsed>=GAME_TIME)endGame();updateHUD()}objects.forEach(o=>o.draw());particles=particles.filter(p=>p.life>0);particles.forEach(p=>{p.update(dt);p.draw()});requestAnimationFrame(frame)}requestAnimationFrame(frame);

stage.addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect();cursor.x=e.clientX-r.left;cursor.y=e.clientY-r.top;cursor.inside=true;ui.gazeCursor.style.left=cursor.x+'px';ui.gazeCursor.style.top=cursor.y+'px';ui.gazeCursor.classList.add('active');if(state==='tutorial'){const pr=ui.practiceGerm.getBoundingClientRect();const over=e.clientX>=pr.left&&e.clientX<=pr.right&&e.clientY>=pr.top&&e.clientY<=pr.bottom;if(over){if(!practiceSince)practiceSince=performance.now();const pct=Math.min(1,(performance.now()-practiceSince)/600);ui.practiceGerm.querySelector('circle').style.strokeDashoffset=339*(1-pct);if(pct>=1&&!practiceLocked){practiceLocked=true;ui.practiceGerm.classList.add('locked');ui.lockStatus.textContent='LOCKED · BLINK NOW';ui.lockStatus.classList.add('ready');ui.tutorialText.textContent='조준 완료! 클릭하거나 Space 키를 눌러 공격하세요.'}}else if(!practiceLocked){practiceSince=0;ui.practiceGerm.querySelector('circle').style.strokeDashoffset=339}}});
stage.addEventListener('pointerleave',()=>{cursor.inside=false;ui.gazeCursor.classList.remove('active')});stage.addEventListener('click',e=>{if(e.target.closest('button'))return;attack()});
document.querySelector('#startButton').onclick=beginTutorial;document.querySelector('#restartButton').onclick=reset;document.querySelector('#soundButton').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=`사운드 ${soundOn?'ON':'OFF'}`;e.currentTarget.setAttribute('aria-pressed',soundOn)};
addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();attack()}if(e.code==='Enter'&&state==='start')beginTutorial();if(e.key.toLowerCase()==='r'&&state==='result')reset()});

