namespace MeteorDefenseVR.Audio
{
    public enum AudioCue
    {
        IntroSpaceAmbient,
        Warning,
        CalibrationPoint,
        CalibrationComplete,
        TargetFocus,
        LockOn,
        Laser,
        MeteorHit,
        MeteorExplosion,
        Score,
        Countdown,
        Launch,
        PlayerDamage,
        BossWarning,
        BossExplosion,
        MissionComplete,
        Result,
        BgmIntro,
        BgmTutorial,
        BgmBattle,
        BgmBoss,
        BgmResult,
        EngineStart,
        GlassHit,
        AirLeak
    }
}
